openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is documentation of contact app
tags:
  # теги, що ви будете використовувати
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.

servers:
  - url: http://localhost:3000
    #посилання на задеплоєний сайт
paths:
  # тут будуть посилання на ендпоінти
  /contacts:
    get:
      $ref: ../swagger/path/contacts/get.yaml
    post:
      $ref: ../swagger/path/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/path/contacts/{contactId}/get.yaml
    patch:
      $ref: ../swagger/path/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/path/contacts/{contactId}/delete.yaml

components:
  schemas:
    contact:
      $ref: ../swagger/components/schemas/contact.yaml
  responses:
    404:
      $ref: ../swagger/components/responses/404.yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
